#!/bin/bash

make;
mpicc -o out/apm1 src/apm1.c -Wall;
mpicc -o out/apm2 src/apm2.c -Wall;
mpicc -o out/apm3 src/apm3.c -Wall;
mpicc -o out/apm4 src/apm4.c -Wall;
echo "\none large pattern large text\n"
./apm 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 1 -n 1 mpirun out/apm1 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 1 -n 1 mpirun out/apm2 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 1 -n 8 mpirun out/apm2 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 8 -n 8 mpirun out/apm2 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 8 -n 64 mpirun out/apm2 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 8 -n 64 mpirun out/apm3 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
salloc -N 8 -n 64 mpirun out/apm4 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;
echo "\nmany small patterns large text\n"
./apm 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATTTC;
salloc -N 1 -n 1 mpirun out/apm1 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 1 -n 1 mpirun out/apm2 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 1 -n 1 mpirun out/apm3 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 1 -n 1 mpirun out/apm4 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 8 -n 64 mpirun out/apm1 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 8 -n 64 mpirun out/apm2 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 8 -n 64 mpirun out/apm3 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;
salloc -N 8 -n 64 mpirun out/apm4 1 dna/large GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCAGTCATATC GGGAGCCCCCATTTC;


mpicc -o out/apm1 src/apm1.c -Wall; salloc -N 1 -n 2 mpirun out/apm1 1 dna/large GGCCAGGGGCACGTGGAAGAAGCTATCGTGGCAAAGGGAGCAGTCATATC;